// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: arbiter/treasury/v1beta/treasury.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Treasury struct {
	TotalReserves int64 `protobuf:"varint,1,opt,name=totalReserves,proto3" json:"totalReserves,omitempty" yaml:"total_reserves"`
	TotalDebt     int64 `protobuf:"varint,2,opt,name=totalDebt,proto3" json:"totalDebt,omitempty" yaml:"total_debt"`
}

func (m *Treasury) Reset()         { *m = Treasury{} }
func (m *Treasury) String() string { return proto.CompactTextString(m) }
func (*Treasury) ProtoMessage()    {}
func (*Treasury) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb09eef98358466, []int{0}
}
func (m *Treasury) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Treasury) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Treasury.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Treasury) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Treasury.Merge(m, src)
}
func (m *Treasury) XXX_Size() int {
	return m.Size()
}
func (m *Treasury) XXX_DiscardUnknown() {
	xxx_messageInfo_Treasury.DiscardUnknown(m)
}

var xxx_messageInfo_Treasury proto.InternalMessageInfo

func (m *Treasury) GetTotalReserves() int64 {
	if m != nil {
		return m.TotalReserves
	}
	return 0
}

func (m *Treasury) GetTotalDebt() int64 {
	if m != nil {
		return m.TotalDebt
	}
	return 0
}

func init() {
	proto.RegisterType((*Treasury)(nil), "arbiter.treasury.v1beta1.Treasury")
}

func init() {
	proto.RegisterFile("arbiter/treasury/v1beta/treasury.proto", fileDescriptor_deb09eef98358466)
}

var fileDescriptor_deb09eef98358466 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0x2c, 0x4a, 0xca,
	0x2c, 0x49, 0x2d, 0xd2, 0x2f, 0x29, 0x4a, 0x4d, 0x2c, 0x2e, 0x2d, 0xaa, 0xd4, 0x2f, 0x33, 0x4c,
	0x4a, 0x2d, 0x49, 0x84, 0xf3, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x24, 0xa0, 0xea, 0xf4,
	0xe0, 0xe2, 0x10, 0x75, 0x86, 0x52, 0x22, 0xe9, 0xf9, 0xe9, 0xf9, 0x60, 0x45, 0xfa, 0x20, 0x16,
	0x44, 0xbd, 0x52, 0x03, 0x23, 0x17, 0x47, 0x08, 0x54, 0xa9, 0x90, 0x3d, 0x17, 0x6f, 0x49, 0x7e,
	0x49, 0x62, 0x4e, 0x50, 0x6a, 0x71, 0x6a, 0x51, 0x59, 0x6a, 0xb1, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0xb3, 0x93, 0xe4, 0xa7, 0x7b, 0xf2, 0xa2, 0x95, 0x89, 0xb9, 0x39, 0x56, 0x4a, 0x60, 0xe9, 0xf8,
	0x22, 0xa8, 0xbc, 0x52, 0x10, 0xaa, 0x7a, 0x21, 0x63, 0x2e, 0x4e, 0xb0, 0x80, 0x4b, 0x6a, 0x52,
	0x89, 0x04, 0x13, 0x58, 0xb3, 0xe8, 0xa7, 0x7b, 0xf2, 0x82, 0xc8, 0x9a, 0x53, 0x52, 0x93, 0x4a,
	0x94, 0x82, 0x10, 0xea, 0x9c, 0x7c, 0x4e, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1,
	0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21,
	0xca, 0x28, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0xbf, 0x38, 0xb1, 0x20,
	0x33, 0x35, 0xaf, 0x58, 0x37, 0x39, 0xbf, 0x38, 0x37, 0xbf, 0x58, 0x1f, 0x16, 0x1c, 0x15, 0x88,
	0x00, 0x29, 0xa9, 0x2c, 0x48, 0x2d, 0x4e, 0x62, 0x03, 0xfb, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x2d, 0xb4, 0x77, 0x54, 0x31, 0x01, 0x00, 0x00,
}

func (m *Treasury) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Treasury) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Treasury) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalDebt != 0 {
		i = encodeVarintTreasury(dAtA, i, uint64(m.TotalDebt))
		i--
		dAtA[i] = 0x10
	}
	if m.TotalReserves != 0 {
		i = encodeVarintTreasury(dAtA, i, uint64(m.TotalReserves))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTreasury(dAtA []byte, offset int, v uint64) int {
	offset -= sovTreasury(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Treasury) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalReserves != 0 {
		n += 1 + sovTreasury(uint64(m.TotalReserves))
	}
	if m.TotalDebt != 0 {
		n += 1 + sovTreasury(uint64(m.TotalDebt))
	}
	return n
}

func sovTreasury(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTreasury(x uint64) (n int) {
	return sovTreasury(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Treasury) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTreasury
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Treasury: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Treasury: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalReserves", wireType)
			}
			m.TotalReserves = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTreasury
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalReserves |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDebt", wireType)
			}
			m.TotalDebt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTreasury
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalDebt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTreasury(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTreasury
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTreasury(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTreasury
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTreasury
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTreasury
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTreasury
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTreasury
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTreasury
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTreasury        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTreasury          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTreasury = fmt.Errorf("proto: unexpected end of group")
)
