// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: arbiter/bond/v1beta/bond.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BondState struct {
	TotalDebt       github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=totalDebt,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"totalDebt" yaml:"total_debt"`
	LastDecay       int64                                  `protobuf:"varint,2,opt,name=lastDecay,proto3" json:"lastDecay,omitempty" yaml:"last_decay"`
	Bonds           []*Bond                                `protobuf:"bytes,3,rep,name=bonds,proto3" json:"bonds,omitempty" yaml:"bonds"`
	IsLiquidityBond bool                                   `protobuf:"varint,4,opt,name=isLiquidityBond,proto3" json:"isLiquidityBond,omitempty" yaml:"is_liquidity_bond"`
	Principle       string                                 `protobuf:"bytes,5,opt,name=principle,proto3" json:"principle,omitempty" yaml:"principle"`
}

func (m *BondState) Reset()         { *m = BondState{} }
func (m *BondState) String() string { return proto.CompactTextString(m) }
func (*BondState) ProtoMessage()    {}
func (*BondState) Descriptor() ([]byte, []int) {
	return fileDescriptor_167fd413a1bcec04, []int{0}
}
func (m *BondState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BondState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BondState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BondState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BondState.Merge(m, src)
}
func (m *BondState) XXX_Size() int {
	return m.Size()
}
func (m *BondState) XXX_DiscardUnknown() {
	xxx_messageInfo_BondState.DiscardUnknown(m)
}

var xxx_messageInfo_BondState proto.InternalMessageInfo

func (m *BondState) GetLastDecay() int64 {
	if m != nil {
		return m.LastDecay
	}
	return 0
}

func (m *BondState) GetBonds() []*Bond {
	if m != nil {
		return m.Bonds
	}
	return nil
}

func (m *BondState) GetIsLiquidityBond() bool {
	if m != nil {
		return m.IsLiquidityBond
	}
	return false
}

func (m *BondState) GetPrinciple() string {
	if m != nil {
		return m.Principle
	}
	return ""
}

type Terms struct {
	// scaling variable for price
	ControlVariable github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=controlVariable,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"controlVariable" yaml:"control_variable"`
	// vestingTerm represented in blocks
	VestingTerm  int64 `protobuf:"varint,2,opt,name=vestingTerm,proto3" json:"vestingTerm,omitempty" yaml:"vesting_term"`
	MinimumPrice int64 `protobuf:"varint,3,opt,name=minimumPrice,proto3" json:"minimumPrice,omitempty" yaml:"minimum_price"`
	MaxPayout    int64 `protobuf:"varint,4,opt,name=maxPayout,proto3" json:"maxPayout,omitempty" yaml:"max_payout"`
	Fee          int64 `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty" yaml:"fee"`
	MaxDebt      int64 `protobuf:"varint,6,opt,name=maxDebt,proto3" json:"maxDebt,omitempty" yaml:"max_debt"`
}

func (m *Terms) Reset()         { *m = Terms{} }
func (m *Terms) String() string { return proto.CompactTextString(m) }
func (*Terms) ProtoMessage()    {}
func (*Terms) Descriptor() ([]byte, []int) {
	return fileDescriptor_167fd413a1bcec04, []int{1}
}
func (m *Terms) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Terms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Terms.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Terms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Terms.Merge(m, src)
}
func (m *Terms) XXX_Size() int {
	return m.Size()
}
func (m *Terms) XXX_DiscardUnknown() {
	xxx_messageInfo_Terms.DiscardUnknown(m)
}

var xxx_messageInfo_Terms proto.InternalMessageInfo

func (m *Terms) GetVestingTerm() int64 {
	if m != nil {
		return m.VestingTerm
	}
	return 0
}

func (m *Terms) GetMinimumPrice() int64 {
	if m != nil {
		return m.MinimumPrice
	}
	return 0
}

func (m *Terms) GetMaxPayout() int64 {
	if m != nil {
		return m.MaxPayout
	}
	return 0
}

func (m *Terms) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Terms) GetMaxDebt() int64 {
	if m != nil {
		return m.MaxDebt
	}
	return 0
}

type Bond struct {
	// # of tokens remaining to be paid
	Payout uint64 `protobuf:"varint,1,opt,name=payout,proto3" json:"payout,omitempty" yaml:"payout"`
	// blocks left for vesting
	Vesting uint64 `protobuf:"varint,2,opt,name=vesting,proto3" json:"vesting,omitempty" yaml:"vesting"`
	// last interaction
	LastBlock uint64 `protobuf:"varint,3,opt,name=lastBlock,proto3" json:"lastBlock,omitempty" yaml:"last_block"`
	//  IN USD, for front end viewing
	PricePaid uint64 `protobuf:"varint,4,opt,name=pricePaid,proto3" json:"pricePaid,omitempty" yaml:"price_paid"`
}

func (m *Bond) Reset()         { *m = Bond{} }
func (m *Bond) String() string { return proto.CompactTextString(m) }
func (*Bond) ProtoMessage()    {}
func (*Bond) Descriptor() ([]byte, []int) {
	return fileDescriptor_167fd413a1bcec04, []int{2}
}
func (m *Bond) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Bond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Bond.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Bond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bond.Merge(m, src)
}
func (m *Bond) XXX_Size() int {
	return m.Size()
}
func (m *Bond) XXX_DiscardUnknown() {
	xxx_messageInfo_Bond.DiscardUnknown(m)
}

var xxx_messageInfo_Bond proto.InternalMessageInfo

func (m *Bond) GetPayout() uint64 {
	if m != nil {
		return m.Payout
	}
	return 0
}

func (m *Bond) GetVesting() uint64 {
	if m != nil {
		return m.Vesting
	}
	return 0
}

func (m *Bond) GetLastBlock() uint64 {
	if m != nil {
		return m.LastBlock
	}
	return 0
}

func (m *Bond) GetPricePaid() uint64 {
	if m != nil {
		return m.PricePaid
	}
	return 0
}

func init() {
	proto.RegisterType((*BondState)(nil), "arbiter.bond.v1beta1.BondState")
	proto.RegisterType((*Terms)(nil), "arbiter.bond.v1beta1.Terms")
	proto.RegisterType((*Bond)(nil), "arbiter.bond.v1beta1.Bond")
}

func init() { proto.RegisterFile("arbiter/bond/v1beta/bond.proto", fileDescriptor_167fd413a1bcec04) }

var fileDescriptor_167fd413a1bcec04 = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x4d, 0x6f, 0xd3, 0x30,
	0x1c, 0xc6, 0x9b, 0xb5, 0xdb, 0xa8, 0x37, 0xf6, 0xe2, 0x15, 0x2d, 0x9a, 0x50, 0x52, 0xf9, 0x80,
	0x8a, 0xc4, 0x52, 0x6d, 0x3b, 0x81, 0x38, 0x85, 0x09, 0x81, 0xc4, 0x61, 0x0a, 0x88, 0x03, 0x97,
	0xc8, 0x49, 0xbc, 0x62, 0x2d, 0x89, 0x43, 0xec, 0x4e, 0xed, 0xb7, 0xe0, 0x63, 0x8d, 0xdb, 0x8e,
	0x88, 0x83, 0x85, 0xda, 0x6f, 0x90, 0x2b, 0x17, 0xe4, 0x97, 0xd2, 0x75, 0x70, 0xe1, 0xd4, 0xa8,
	0xcf, 0xef, 0xf9, 0xdb, 0x7e, 0xfc, 0xc8, 0xc0, 0xc3, 0x75, 0x42, 0x05, 0xa9, 0x87, 0x09, 0x2b,
	0xb3, 0xe1, 0xf5, 0x49, 0x42, 0x04, 0xd6, 0xdf, 0x41, 0x55, 0x33, 0xc1, 0x60, 0xcf, 0xea, 0x81,
	0xfe, 0xcf, 0xe8, 0x27, 0x47, 0xbd, 0x11, 0x1b, 0x31, 0x0d, 0x0c, 0xd5, 0x97, 0x61, 0xd1, 0x7c,
	0x0d, 0x74, 0x43, 0x56, 0x66, 0xef, 0x05, 0x16, 0x04, 0x62, 0xd0, 0x15, 0x4c, 0xe0, 0xfc, 0x9c,
	0x24, 0xc2, 0x75, 0xfa, 0xce, 0xa0, 0x1b, 0xbe, 0xba, 0x91, 0x7e, 0xeb, 0x87, 0xf4, 0x9f, 0x8c,
	0xa8, 0xf8, 0x3c, 0x4e, 0x82, 0x94, 0x15, 0xc3, 0x94, 0xf1, 0x82, 0x71, 0xfb, 0x73, 0xcc, 0xb3,
	0xab, 0xa1, 0x98, 0x56, 0x84, 0x07, 0xe7, 0x24, 0x6d, 0xa4, 0xbf, 0x3f, 0xc5, 0x45, 0xfe, 0x02,
	0xe9, 0x41, 0x71, 0x46, 0x12, 0x81, 0xa2, 0xe5, 0x54, 0x78, 0x06, 0xba, 0x39, 0xe6, 0xe2, 0x9c,
	0xa4, 0x78, 0xea, 0xae, 0xf5, 0x9d, 0x41, 0x3b, 0x7c, 0xb4, 0x34, 0x29, 0x29, 0xce, 0x94, 0x86,
	0xa2, 0x25, 0x07, 0x43, 0xb0, 0xae, 0xce, 0xc2, 0xdd, 0x76, 0xbf, 0x3d, 0xd8, 0x3a, 0x3d, 0x0a,
	0xfe, 0x75, 0xc2, 0x40, 0x9d, 0x23, 0xdc, 0x6b, 0xa4, 0xbf, 0x6d, 0x86, 0x69, 0x0b, 0x8a, 0x8c,
	0x15, 0xbe, 0x06, 0xbb, 0x94, 0xbf, 0xa3, 0x5f, 0xc6, 0x34, 0xa3, 0x62, 0xaa, 0x58, 0xb7, 0xd3,
	0x77, 0x06, 0x0f, 0xc2, 0xc7, 0x8d, 0xf4, 0x5d, 0xe3, 0xa0, 0x3c, 0xce, 0x17, 0x44, 0xac, 0x6c,
	0x28, 0xba, 0x6f, 0x82, 0xa7, 0xa0, 0x5b, 0xd5, 0xb4, 0x4c, 0x69, 0x95, 0x13, 0x77, 0x5d, 0x67,
	0xd4, 0x6b, 0xa4, 0xbf, 0x67, 0x26, 0xfc, 0x91, 0x50, 0xb4, 0xc4, 0xd0, 0xaf, 0x35, 0xb0, 0xfe,
	0x81, 0xd4, 0x05, 0x87, 0x1c, 0xec, 0xa6, 0xac, 0x14, 0x35, 0xcb, 0x3f, 0xe2, 0x9a, 0xe2, 0x24,
	0x27, 0x36, 0xe7, 0xb7, 0xff, 0x9d, 0xf3, 0xa1, 0x59, 0xd1, 0x8e, 0x8b, 0xaf, 0xed, 0x3c, 0x14,
	0xdd, 0x5f, 0x01, 0x3e, 0x07, 0x5b, 0xd7, 0x84, 0x0b, 0x5a, 0x8e, 0xd4, 0x26, 0x6c, 0xea, 0x87,
	0x8d, 0xf4, 0x0f, 0xcc, 0x08, 0x2b, 0xc6, 0x82, 0xd4, 0x05, 0x8a, 0xee, 0xb2, 0xf0, 0x25, 0xd8,
	0x2e, 0x68, 0x49, 0x8b, 0x71, 0x71, 0x51, 0xd3, 0x94, 0xb8, 0x6d, 0xed, 0x75, 0x1b, 0xe9, 0xf7,
	0x8c, 0xd7, 0xaa, 0x71, 0xa5, 0x64, 0x14, 0xad, 0xd0, 0xea, 0xb2, 0x0b, 0x3c, 0xb9, 0xc0, 0x53,
	0x36, 0x16, 0x3a, 0xed, 0x95, 0xcb, 0x2e, 0xf0, 0x24, 0xae, 0xb4, 0x86, 0xa2, 0x25, 0x07, 0xfb,
	0xa0, 0x7d, 0x49, 0x4c, 0xb4, 0xed, 0x70, 0xa7, 0x91, 0x3e, 0x30, 0xf8, 0x25, 0x21, 0x28, 0x52,
	0x12, 0x3c, 0x06, 0x9b, 0x05, 0x9e, 0xe8, 0x92, 0x6e, 0x68, 0xea, 0xa0, 0x91, 0xfe, 0xee, 0x72,
	0xa8, 0x29, 0xdd, 0x82, 0x41, 0xdf, 0x1c, 0xd0, 0xd1, 0x57, 0xf7, 0x14, 0x6c, 0x98, 0xf5, 0x74,
	0xe6, 0x9d, 0x70, 0xbf, 0x91, 0xfe, 0x43, 0x7b, 0x6f, 0x76, 0x1f, 0x16, 0x80, 0xcf, 0xc0, 0xa6,
	0x8d, 0x41, 0xc7, 0xd5, 0x09, 0x61, 0x23, 0xfd, 0x9d, 0x95, 0xb8, 0x50, 0xb4, 0x40, 0x16, 0xa5,
	0x0e, 0x73, 0x96, 0x5e, 0xe9, 0x88, 0x3a, 0x7f, 0x95, 0x3a, 0x51, 0x9a, 0x2d, 0xb5, 0xe6, 0x94,
	0x49, 0x87, 0x76, 0x81, 0xa9, 0xa9, 0xe2, 0x8a, 0x49, 0x4b, 0x71, 0x85, 0x69, 0x66, 0x9a, 0x64,
	0xb8, 0xf0, 0xcd, 0xcd, 0xcc, 0x73, 0x6e, 0x67, 0x9e, 0xf3, 0x73, 0xe6, 0x39, 0x5f, 0xe7, 0x5e,
	0xeb, 0x76, 0xee, 0xb5, 0xbe, 0xcf, 0xbd, 0xd6, 0xa7, 0xe0, 0x4e, 0x71, 0x38, 0xae, 0x28, 0x29,
	0xf9, 0xb1, 0x2d, 0xd0, 0xe2, 0xbd, 0x98, 0x98, 0x17, 0x43, 0x97, 0x28, 0xd9, 0xd0, 0x0f, 0xc0,
	0xd9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x16, 0xb3, 0x1a, 0xdd, 0x4e, 0x04, 0x00, 0x00,
}

func (m *BondState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BondState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BondState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Principle) > 0 {
		i -= len(m.Principle)
		copy(dAtA[i:], m.Principle)
		i = encodeVarintBond(dAtA, i, uint64(len(m.Principle)))
		i--
		dAtA[i] = 0x2a
	}
	if m.IsLiquidityBond {
		i--
		if m.IsLiquidityBond {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Bonds) > 0 {
		for iNdEx := len(m.Bonds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Bonds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBond(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.LastDecay != 0 {
		i = encodeVarintBond(dAtA, i, uint64(m.LastDecay))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.TotalDebt.Size()
		i -= size
		if _, err := m.TotalDebt.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBond(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Terms) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Terms) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Terms) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxDebt != 0 {
		i = encodeVarintBond(dAtA, i, uint64(m.MaxDebt))
		i--
		dAtA[i] = 0x30
	}
	if m.Fee != 0 {
		i = encodeVarintBond(dAtA, i, uint64(m.Fee))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxPayout != 0 {
		i = encodeVarintBond(dAtA, i, uint64(m.MaxPayout))
		i--
		dAtA[i] = 0x20
	}
	if m.MinimumPrice != 0 {
		i = encodeVarintBond(dAtA, i, uint64(m.MinimumPrice))
		i--
		dAtA[i] = 0x18
	}
	if m.VestingTerm != 0 {
		i = encodeVarintBond(dAtA, i, uint64(m.VestingTerm))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.ControlVariable.Size()
		i -= size
		if _, err := m.ControlVariable.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBond(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Bond) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Bond) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Bond) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PricePaid != 0 {
		i = encodeVarintBond(dAtA, i, uint64(m.PricePaid))
		i--
		dAtA[i] = 0x20
	}
	if m.LastBlock != 0 {
		i = encodeVarintBond(dAtA, i, uint64(m.LastBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.Vesting != 0 {
		i = encodeVarintBond(dAtA, i, uint64(m.Vesting))
		i--
		dAtA[i] = 0x10
	}
	if m.Payout != 0 {
		i = encodeVarintBond(dAtA, i, uint64(m.Payout))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBond(dAtA []byte, offset int, v uint64) int {
	offset -= sovBond(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BondState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalDebt.Size()
	n += 1 + l + sovBond(uint64(l))
	if m.LastDecay != 0 {
		n += 1 + sovBond(uint64(m.LastDecay))
	}
	if len(m.Bonds) > 0 {
		for _, e := range m.Bonds {
			l = e.Size()
			n += 1 + l + sovBond(uint64(l))
		}
	}
	if m.IsLiquidityBond {
		n += 2
	}
	l = len(m.Principle)
	if l > 0 {
		n += 1 + l + sovBond(uint64(l))
	}
	return n
}

func (m *Terms) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ControlVariable.Size()
	n += 1 + l + sovBond(uint64(l))
	if m.VestingTerm != 0 {
		n += 1 + sovBond(uint64(m.VestingTerm))
	}
	if m.MinimumPrice != 0 {
		n += 1 + sovBond(uint64(m.MinimumPrice))
	}
	if m.MaxPayout != 0 {
		n += 1 + sovBond(uint64(m.MaxPayout))
	}
	if m.Fee != 0 {
		n += 1 + sovBond(uint64(m.Fee))
	}
	if m.MaxDebt != 0 {
		n += 1 + sovBond(uint64(m.MaxDebt))
	}
	return n
}

func (m *Bond) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Payout != 0 {
		n += 1 + sovBond(uint64(m.Payout))
	}
	if m.Vesting != 0 {
		n += 1 + sovBond(uint64(m.Vesting))
	}
	if m.LastBlock != 0 {
		n += 1 + sovBond(uint64(m.LastBlock))
	}
	if m.PricePaid != 0 {
		n += 1 + sovBond(uint64(m.PricePaid))
	}
	return n
}

func sovBond(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBond(x uint64) (n int) {
	return sovBond(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BondState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBond
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BondState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BondState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDebt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalDebt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastDecay", wireType)
			}
			m.LastDecay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastDecay |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bonds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBond
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bonds = append(m.Bonds, &Bond{})
			if err := m.Bonds[len(m.Bonds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsLiquidityBond", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsLiquidityBond = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Principle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Principle = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBond(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBond
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Terms) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBond
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Terms: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Terms: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControlVariable", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ControlVariable.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingTerm", wireType)
			}
			m.VestingTerm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingTerm |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumPrice", wireType)
			}
			m.MinimumPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinimumPrice |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPayout", wireType)
			}
			m.MaxPayout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPayout |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			m.Fee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Fee |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDebt", wireType)
			}
			m.MaxDebt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDebt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBond(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBond
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Bond) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBond
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Bond: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Bond: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payout", wireType)
			}
			m.Payout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Payout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vesting", wireType)
			}
			m.Vesting = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vesting |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastBlock", wireType)
			}
			m.LastBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PricePaid", wireType)
			}
			m.PricePaid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PricePaid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBond(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBond
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBond(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBond
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBond
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBond
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBond
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBond
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBond
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBond        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBond          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBond = fmt.Errorf("proto: unexpected end of group")
)
