// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: arbiter/bond/v1beta/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryRedeemableRequest struct {
	Bonder string `protobuf:"bytes,1,opt,name=bonder,proto3" json:"bonder,omitempty"`
}

func (m *QueryRedeemableRequest) Reset()         { *m = QueryRedeemableRequest{} }
func (m *QueryRedeemableRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRedeemableRequest) ProtoMessage()    {}
func (*QueryRedeemableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5433add66a39037, []int{0}
}
func (m *QueryRedeemableRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRedeemableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRedeemableRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRedeemableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRedeemableRequest.Merge(m, src)
}
func (m *QueryRedeemableRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRedeemableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRedeemableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRedeemableRequest proto.InternalMessageInfo

type QueryRedeemabeResponse struct {
	Coin *types.Coin `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
}

func (m *QueryRedeemabeResponse) Reset()         { *m = QueryRedeemabeResponse{} }
func (m *QueryRedeemabeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRedeemabeResponse) ProtoMessage()    {}
func (*QueryRedeemabeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5433add66a39037, []int{1}
}
func (m *QueryRedeemabeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRedeemabeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRedeemabeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRedeemabeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRedeemabeResponse.Merge(m, src)
}
func (m *QueryRedeemabeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRedeemabeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRedeemabeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRedeemabeResponse proto.InternalMessageInfo

func (m *QueryRedeemabeResponse) GetCoin() *types.Coin {
	if m != nil {
		return m.Coin
	}
	return nil
}

type QueryRiskFreePriceRequest struct {
	BondDenom string `protobuf:"bytes,1,opt,name=bond_denom,json=bondDenom,proto3" json:"bond_denom,omitempty"`
}

func (m *QueryRiskFreePriceRequest) Reset()         { *m = QueryRiskFreePriceRequest{} }
func (m *QueryRiskFreePriceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRiskFreePriceRequest) ProtoMessage()    {}
func (*QueryRiskFreePriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5433add66a39037, []int{2}
}
func (m *QueryRiskFreePriceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRiskFreePriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRiskFreePriceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRiskFreePriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRiskFreePriceRequest.Merge(m, src)
}
func (m *QueryRiskFreePriceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRiskFreePriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRiskFreePriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRiskFreePriceRequest proto.InternalMessageInfo

type QueryRiskFreePriceResponse struct {
	Price *github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=price,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"price,omitempty"`
}

func (m *QueryRiskFreePriceResponse) Reset()         { *m = QueryRiskFreePriceResponse{} }
func (m *QueryRiskFreePriceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRiskFreePriceResponse) ProtoMessage()    {}
func (*QueryRiskFreePriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5433add66a39037, []int{3}
}
func (m *QueryRiskFreePriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRiskFreePriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRiskFreePriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRiskFreePriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRiskFreePriceResponse.Merge(m, src)
}
func (m *QueryRiskFreePriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRiskFreePriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRiskFreePriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRiskFreePriceResponse proto.InternalMessageInfo

type QueryPremiumRequest struct {
	BondDenom string `protobuf:"bytes,1,opt,name=bond_denom,json=bondDenom,proto3" json:"bond_denom,omitempty"`
}

func (m *QueryPremiumRequest) Reset()         { *m = QueryPremiumRequest{} }
func (m *QueryPremiumRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPremiumRequest) ProtoMessage()    {}
func (*QueryPremiumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5433add66a39037, []int{4}
}
func (m *QueryPremiumRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPremiumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPremiumRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPremiumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPremiumRequest.Merge(m, src)
}
func (m *QueryPremiumRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPremiumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPremiumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPremiumRequest proto.InternalMessageInfo

type QueryPremiumResponse struct {
	Premium *github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=premium,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"premium,omitempty"`
}

func (m *QueryPremiumResponse) Reset()         { *m = QueryPremiumResponse{} }
func (m *QueryPremiumResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPremiumResponse) ProtoMessage()    {}
func (*QueryPremiumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5433add66a39037, []int{5}
}
func (m *QueryPremiumResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPremiumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPremiumResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPremiumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPremiumResponse.Merge(m, src)
}
func (m *QueryPremiumResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPremiumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPremiumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPremiumResponse proto.InternalMessageInfo

type QueryBondInfoRequest struct {
	BondDenom string `protobuf:"bytes,1,opt,name=bond_denom,json=bondDenom,proto3" json:"bond_denom,omitempty"`
}

func (m *QueryBondInfoRequest) Reset()         { *m = QueryBondInfoRequest{} }
func (m *QueryBondInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBondInfoRequest) ProtoMessage()    {}
func (*QueryBondInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5433add66a39037, []int{6}
}
func (m *QueryBondInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBondInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBondInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBondInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBondInfoRequest.Merge(m, src)
}
func (m *QueryBondInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBondInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBondInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBondInfoRequest proto.InternalMessageInfo

type QueryBondInfoResponse struct {
	RiskFreePrice  *github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=risk_free_price,json=riskFreePrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"risk_free_price,omitempty"`
	Premium        *github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=premium,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"premium,omitempty"`
	ExecutingPrice *github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=executing_price,json=executingPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"executing_price,omitempty"`
}

func (m *QueryBondInfoResponse) Reset()         { *m = QueryBondInfoResponse{} }
func (m *QueryBondInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBondInfoResponse) ProtoMessage()    {}
func (*QueryBondInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5433add66a39037, []int{7}
}
func (m *QueryBondInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBondInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBondInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBondInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBondInfoResponse.Merge(m, src)
}
func (m *QueryBondInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBondInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBondInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBondInfoResponse proto.InternalMessageInfo

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5433add66a39037, []int{8}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5433add66a39037, []int{9}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func init() {
	proto.RegisterType((*QueryRedeemableRequest)(nil), "arbiter.bond.v1beta1.QueryRedeemableRequest")
	proto.RegisterType((*QueryRedeemabeResponse)(nil), "arbiter.bond.v1beta1.QueryRedeemabeResponse")
	proto.RegisterType((*QueryRiskFreePriceRequest)(nil), "arbiter.bond.v1beta1.QueryRiskFreePriceRequest")
	proto.RegisterType((*QueryRiskFreePriceResponse)(nil), "arbiter.bond.v1beta1.QueryRiskFreePriceResponse")
	proto.RegisterType((*QueryPremiumRequest)(nil), "arbiter.bond.v1beta1.QueryPremiumRequest")
	proto.RegisterType((*QueryPremiumResponse)(nil), "arbiter.bond.v1beta1.QueryPremiumResponse")
	proto.RegisterType((*QueryBondInfoRequest)(nil), "arbiter.bond.v1beta1.QueryBondInfoRequest")
	proto.RegisterType((*QueryBondInfoResponse)(nil), "arbiter.bond.v1beta1.QueryBondInfoResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "arbiter.bond.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "arbiter.bond.v1beta1.QueryParamsResponse")
}

func init() { proto.RegisterFile("arbiter/bond/v1beta/query.proto", fileDescriptor_c5433add66a39037) }

var fileDescriptor_c5433add66a39037 = []byte{
	// 689 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0x4f, 0x4f, 0x13, 0x4f,
	0x18, 0xc7, 0xbb, 0xfc, 0xa0, 0xc0, 0xfc, 0x82, 0x24, 0x63, 0x25, 0xb2, 0xc1, 0x2d, 0xd9, 0x18,
	0xc3, 0xdf, 0x1d, 0x5b, 0x39, 0xf5, 0xa0, 0x06, 0x1b, 0xff, 0xdc, 0x60, 0xbd, 0x19, 0x23, 0xd9,
	0x6d, 0x1f, 0xea, 0x04, 0x76, 0x66, 0x99, 0xd9, 0x1a, 0x88, 0xe1, 0xa2, 0x89, 0xf1, 0xa6, 0x89,
	0x5e, 0x8c, 0x17, 0x5e, 0x81, 0xaf, 0x83, 0x23, 0x89, 0x17, 0xe3, 0x81, 0x18, 0xf0, 0xe0, 0xcb,
	0x30, 0x3b, 0x33, 0xad, 0x5d, 0xb2, 0x34, 0x85, 0x53, 0xdb, 0xd9, 0xef, 0xf3, 0x9d, 0xcf, 0x3c,
	0xf3, 0x7c, 0xbb, 0xa8, 0x1c, 0x88, 0x90, 0x26, 0x20, 0x48, 0xc8, 0x59, 0x93, 0xbc, 0xaa, 0x84,
	0x90, 0x04, 0x64, 0xa7, 0x0d, 0x62, 0xcf, 0x8b, 0x05, 0x4f, 0x38, 0x2e, 0x19, 0x81, 0x97, 0x0a,
	0x3c, 0x2d, 0xa8, 0xd8, 0xa5, 0x16, 0x6f, 0x71, 0x25, 0x20, 0xe9, 0x37, 0xad, 0xb5, 0x67, 0x5a,
	0x9c, 0xb7, 0xb6, 0x81, 0x04, 0x31, 0x25, 0x01, 0x63, 0x3c, 0x09, 0x12, 0xca, 0x99, 0x34, 0x4f,
	0x9d, 0x06, 0x97, 0x11, 0x97, 0x24, 0x0c, 0x24, 0x98, 0x9d, 0x2a, 0xa4, 0xc1, 0x29, 0x33, 0xcf,
	0x67, 0xf3, 0x50, 0xe2, 0x40, 0x04, 0x91, 0x71, 0x70, 0x6b, 0x68, 0x6a, 0x3d, 0x45, 0xf3, 0xa1,
	0x09, 0x10, 0x05, 0xe1, 0x36, 0xf8, 0xb0, 0xd3, 0x06, 0x99, 0xe0, 0x29, 0x54, 0x4c, 0xab, 0x40,
	0x5c, 0xb7, 0x66, 0xad, 0xb9, 0x71, 0xdf, 0xfc, 0xaa, 0x8d, 0xbd, 0x3f, 0x28, 0x17, 0xfe, 0x1c,
	0x94, 0x0b, 0xee, 0xa3, 0x33, 0xb5, 0xe0, 0x83, 0x8c, 0x39, 0x93, 0x80, 0x97, 0xd1, 0x70, 0x4a,
	0xa1, 0x2a, 0xff, 0xaf, 0x4e, 0x7b, 0x1a, 0xd3, 0x4b, 0x31, 0x3b, 0xe7, 0xf5, 0x1e, 0x70, 0xca,
	0x7c, 0x25, 0x73, 0xeb, 0x68, 0x5a, 0x1b, 0x51, 0xb9, 0xf5, 0x50, 0x00, 0xac, 0x09, 0xda, 0xe8,
	0x72, 0xdc, 0x40, 0x28, 0xdd, 0x79, 0xa3, 0x09, 0x8c, 0x47, 0x86, 0x65, 0x3c, 0x5d, 0xa9, 0xa7,
	0x0b, 0x3d, 0x38, 0x2f, 0x90, 0x9d, 0xe7, 0x62, 0x90, 0xee, 0xa3, 0x91, 0x38, 0x5d, 0xd0, 0x0e,
	0xab, 0x0b, 0x3f, 0x8f, 0xcb, 0xb7, 0x5a, 0x34, 0x79, 0xd9, 0x0e, 0xbd, 0x06, 0x8f, 0x88, 0x69,
	0xa4, 0xfe, 0x58, 0x96, 0xcd, 0x2d, 0x92, 0xec, 0xc5, 0x20, 0xbd, 0x3a, 0x34, 0x7c, 0x5d, 0xe8,
	0xde, 0x45, 0x57, 0x95, 0xff, 0x9a, 0x80, 0x88, 0xb6, 0xa3, 0x0b, 0xf3, 0x3d, 0x47, 0xa5, 0x6c,
	0xbd, 0x21, 0xab, 0xa3, 0xd1, 0x58, 0x2f, 0x5d, 0x82, 0xad, 0x53, 0xea, 0xde, 0x33, 0xee, 0xab,
	0x9c, 0x35, 0x9f, 0xb0, 0x4d, 0x7e, 0x61, 0xbc, 0x77, 0x43, 0xe8, 0xda, 0x19, 0x07, 0x03, 0xe8,
	0xa3, 0x49, 0x41, 0xe5, 0xd6, 0xc6, 0xa6, 0x00, 0xd8, 0xb8, 0x6c, 0x13, 0x27, 0x44, 0xef, 0xb5,
	0xf4, 0x1e, 0x7a, 0xe8, 0xd2, 0x87, 0xc6, 0x4f, 0xd1, 0x24, 0xec, 0x42, 0xa3, 0x9d, 0x50, 0xd6,
	0x32, 0x64, 0xff, 0x5d, 0xd8, 0xed, 0x4a, 0xd7, 0x42, 0xa1, 0xb9, 0x25, 0x84, 0xf5, 0x3d, 0xa9,
	0x9c, 0x98, 0x3e, 0xba, 0xeb, 0x9d, 0xdb, 0x37, 0xab, 0xa6, 0x37, 0x35, 0x54, 0xd4, 0x79, 0x32,
	0xb3, 0x3e, 0xe3, 0xe5, 0x85, 0xdb, 0xd3, 0x55, 0xab, 0xc3, 0x87, 0xc7, 0xe5, 0x82, 0x6f, 0x2a,
	0xaa, 0x1f, 0x8a, 0x68, 0x44, 0x79, 0xe2, 0xaf, 0x16, 0x42, 0xff, 0x12, 0x88, 0x97, 0xf2, 0x4d,
	0xf2, 0x83, 0x6a, 0x0f, 0xa2, 0xee, 0xe6, 0xc0, 0xad, 0xbc, 0xf9, 0xfe, 0xfb, 0xd3, 0xd0, 0x22,
	0x9e, 0x27, 0x39, 0xff, 0x0d, 0x15, 0x22, 0xba, 0xf6, 0xe4, 0xb5, 0x0e, 0xfc, 0x3e, 0xfe, 0x66,
	0xa1, 0x89, 0x4c, 0xa8, 0x30, 0xe9, 0xb7, 0x65, 0x4e, 0x88, 0xed, 0xdb, 0x83, 0x17, 0x18, 0xce,
	0x9a, 0xe2, 0x5c, 0xc1, 0xd5, 0x73, 0x38, 0xb3, 0x03, 0xa9, 0x61, 0xf5, 0x90, 0xef, 0xe3, 0xcf,
	0x16, 0x1a, 0x35, 0x29, 0xc3, 0xf3, 0x7d, 0x76, 0xce, 0x26, 0xd9, 0x5e, 0x18, 0x44, 0x6a, 0xf0,
	0xaa, 0x0a, 0x6f, 0x09, 0x2f, 0xe4, 0xe3, 0x99, 0x01, 0xcd, 0x62, 0x7d, 0xb1, 0xd0, 0x58, 0x27,
	0x5c, 0xb8, 0xdf, 0x66, 0x67, 0x32, 0x6c, 0x2f, 0x0e, 0xa4, 0x35, 0x64, 0x2b, 0x8a, 0xcc, 0xc3,
	0x4b, 0xf9, 0x64, 0x0a, 0x88, 0xb2, 0x4d, 0x9e, 0x65, 0x7b, 0x6b, 0xa1, 0xa2, 0x1e, 0x52, 0x3c,
	0xd7, 0xaf, 0x0d, 0xbd, 0x99, 0xb0, 0xe7, 0x07, 0x50, 0x1a, 0xaa, 0x9b, 0x8a, 0xca, 0xc1, 0x33,
	0xe7, 0xf4, 0x4b, 0xe7, 0xe3, 0xf1, 0xe1, 0x89, 0x63, 0x1d, 0x9d, 0x38, 0xd6, 0xaf, 0x13, 0xc7,
	0xfa, 0x78, 0xea, 0x14, 0x8e, 0x4e, 0x9d, 0xc2, 0x8f, 0x53, 0xa7, 0xf0, 0xcc, 0xeb, 0x09, 0xb3,
	0x0c, 0x62, 0x0a, 0x4c, 0x2e, 0x9b, 0x50, 0x77, 0x0c, 0x77, 0xb5, 0xa5, 0x0a, 0x76, 0x58, 0x54,
	0xaf, 0xb7, 0x3b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x7e, 0x92, 0xd0, 0x8d, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Redeemable(ctx context.Context, in *QueryRedeemableRequest, opts ...grpc.CallOption) (*QueryRedeemabeResponse, error)
	RiskFreePrice(ctx context.Context, in *QueryRiskFreePriceRequest, opts ...grpc.CallOption) (*QueryRiskFreePriceResponse, error)
	Premium(ctx context.Context, in *QueryPremiumRequest, opts ...grpc.CallOption) (*QueryPremiumResponse, error)
	BondInfo(ctx context.Context, in *QueryBondInfoRequest, opts ...grpc.CallOption) (*QueryBondInfoResponse, error)
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Redeemable(ctx context.Context, in *QueryRedeemableRequest, opts ...grpc.CallOption) (*QueryRedeemabeResponse, error) {
	out := new(QueryRedeemabeResponse)
	err := c.cc.Invoke(ctx, "/arbiter.bond.v1beta1.Query/Redeemable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RiskFreePrice(ctx context.Context, in *QueryRiskFreePriceRequest, opts ...grpc.CallOption) (*QueryRiskFreePriceResponse, error) {
	out := new(QueryRiskFreePriceResponse)
	err := c.cc.Invoke(ctx, "/arbiter.bond.v1beta1.Query/RiskFreePrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Premium(ctx context.Context, in *QueryPremiumRequest, opts ...grpc.CallOption) (*QueryPremiumResponse, error) {
	out := new(QueryPremiumResponse)
	err := c.cc.Invoke(ctx, "/arbiter.bond.v1beta1.Query/Premium", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BondInfo(ctx context.Context, in *QueryBondInfoRequest, opts ...grpc.CallOption) (*QueryBondInfoResponse, error) {
	out := new(QueryBondInfoResponse)
	err := c.cc.Invoke(ctx, "/arbiter.bond.v1beta1.Query/BondInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/arbiter.bond.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Redeemable(context.Context, *QueryRedeemableRequest) (*QueryRedeemabeResponse, error)
	RiskFreePrice(context.Context, *QueryRiskFreePriceRequest) (*QueryRiskFreePriceResponse, error)
	Premium(context.Context, *QueryPremiumRequest) (*QueryPremiumResponse, error)
	BondInfo(context.Context, *QueryBondInfoRequest) (*QueryBondInfoResponse, error)
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Redeemable(ctx context.Context, req *QueryRedeemableRequest) (*QueryRedeemabeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Redeemable not implemented")
}
func (*UnimplementedQueryServer) RiskFreePrice(ctx context.Context, req *QueryRiskFreePriceRequest) (*QueryRiskFreePriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RiskFreePrice not implemented")
}
func (*UnimplementedQueryServer) Premium(ctx context.Context, req *QueryPremiumRequest) (*QueryPremiumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Premium not implemented")
}
func (*UnimplementedQueryServer) BondInfo(ctx context.Context, req *QueryBondInfoRequest) (*QueryBondInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BondInfo not implemented")
}
func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Redeemable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRedeemableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Redeemable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arbiter.bond.v1beta1.Query/Redeemable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Redeemable(ctx, req.(*QueryRedeemableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RiskFreePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRiskFreePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RiskFreePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arbiter.bond.v1beta1.Query/RiskFreePrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RiskFreePrice(ctx, req.(*QueryRiskFreePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Premium_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPremiumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Premium(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arbiter.bond.v1beta1.Query/Premium",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Premium(ctx, req.(*QueryPremiumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BondInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBondInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BondInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arbiter.bond.v1beta1.Query/BondInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BondInfo(ctx, req.(*QueryBondInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arbiter.bond.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "arbiter.bond.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Redeemable",
			Handler:    _Query_Redeemable_Handler,
		},
		{
			MethodName: "RiskFreePrice",
			Handler:    _Query_RiskFreePrice_Handler,
		},
		{
			MethodName: "Premium",
			Handler:    _Query_Premium_Handler,
		},
		{
			MethodName: "BondInfo",
			Handler:    _Query_BondInfo_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arbiter/bond/v1beta/query.proto",
}

func (m *QueryRedeemableRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRedeemableRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRedeemableRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Bonder) > 0 {
		i -= len(m.Bonder)
		copy(dAtA[i:], m.Bonder)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Bonder)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRedeemabeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRedeemabeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRedeemabeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Coin != nil {
		{
			size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRiskFreePriceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRiskFreePriceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRiskFreePriceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BondDenom) > 0 {
		i -= len(m.BondDenom)
		copy(dAtA[i:], m.BondDenom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BondDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRiskFreePriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRiskFreePriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRiskFreePriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Price != nil {
		{
			size := m.Price.Size()
			i -= size
			if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPremiumRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPremiumRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPremiumRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BondDenom) > 0 {
		i -= len(m.BondDenom)
		copy(dAtA[i:], m.BondDenom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BondDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPremiumResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPremiumResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPremiumResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Premium != nil {
		{
			size := m.Premium.Size()
			i -= size
			if _, err := m.Premium.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBondInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBondInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBondInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BondDenom) > 0 {
		i -= len(m.BondDenom)
		copy(dAtA[i:], m.BondDenom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BondDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBondInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBondInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBondInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExecutingPrice != nil {
		{
			size := m.ExecutingPrice.Size()
			i -= size
			if _, err := m.ExecutingPrice.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Premium != nil {
		{
			size := m.Premium.Size()
			i -= size
			if _, err := m.Premium.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.RiskFreePrice != nil {
		{
			size := m.RiskFreePrice.Size()
			i -= size
			if _, err := m.RiskFreePrice.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryRedeemableRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Bonder)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRedeemabeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Coin != nil {
		l = m.Coin.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRiskFreePriceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BondDenom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRiskFreePriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Price != nil {
		l = m.Price.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPremiumRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BondDenom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPremiumResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Premium != nil {
		l = m.Premium.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBondInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BondDenom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBondInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RiskFreePrice != nil {
		l = m.RiskFreePrice.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Premium != nil {
		l = m.Premium.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.ExecutingPrice != nil {
		l = m.ExecutingPrice.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryRedeemableRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRedeemableRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRedeemableRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bonder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bonder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRedeemabeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRedeemabeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRedeemabeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Coin == nil {
				m.Coin = &types.Coin{}
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRiskFreePriceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRiskFreePriceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRiskFreePriceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRiskFreePriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRiskFreePriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRiskFreePriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Dec
			m.Price = &v
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPremiumRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPremiumRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPremiumRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPremiumResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPremiumResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPremiumResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Premium", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Dec
			m.Premium = &v
			if err := m.Premium.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBondInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBondInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBondInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBondInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBondInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBondInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RiskFreePrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Dec
			m.RiskFreePrice = &v
			if err := m.RiskFreePrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Premium", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Dec
			m.Premium = &v
			if err := m.Premium.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutingPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Dec
			m.ExecutingPrice = &v
			if err := m.ExecutingPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
